---
- name: Print the networks variable
  debug:
    var: networks

- name: Define and configure multiple networks
  community.libvirt.virt_net:
    command: define
    name: "{{ item.network_name }}"
    xml: "{{ lookup('template', 'network/network.xml.j2', item) }}"
  loop: "{{ networks }}"
  loop_control:
    loop_var: item
  notify:
    - Start the network
    - Ensure that the network is active
    - Ensure that the network autostart is enabled